name: Docker Compose Actions Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build --no-cache --force-rm 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/hello-fastapi
          tags: latest
          dockerfile: Dockerfile
          add_git_labels: true
          cache_froms: ${{ secrets.DOCKER_USERNAME }}/hello-fastapi:latest
          cache_to: type=inline
      - name: image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
      - name: image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}