  name: Setup PostgreSQL
  on: [push]
  uses: Harmon758/postgresql-action@v1.0.0
  with:
    # Version of PostgreSQL to use
    postgresql version: default
    # POSTGRES_DB - name for the default database that is created
    postgresql db: hello_fastapi_dev
    # POSTGRES_USER - create the specified user with superuser power
    postgresql user: hello_fastapi
    # POSTGRES_PASSWORD - superuser password
    postgresql password: hello_fastapi
